import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { ArrowLeft, ArrowRight, Bookmark, Building2, Check, ChevronRight, ExternalLink, HeartPulse, Hospital, MapPin, Navigation, Phone, Search, ShieldCheck, Sparkles, Stethoscope, X } from 'lucide-react-native';
import { CareDirectory, CareListing, mapsUrl } from './directory';

export const theme = { blue: '#285AE8', navy: '#14274C', muted: '#748099', pale: '#EDF2FF', line: '#E4E9F2', bg: '#F6F8FC' };
type Kind = 'All' | CareListing['kind'];
const icons = { Doctor: Stethoscope, Hospital, Clinic: Building2 };
const colors = { Doctor: ['#EDF2FF', '#4269DE'], Hospital: ['#E7F5F0', '#248F72'], Clinic: ['#FFF2E8', '#CB8555'] };
function Chip({ label, active, onPress }: { label: string; active?: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected: !!active }} onPress={onPress} style={[s.chip, active && s.chipActive]}><Text style={[s.chipText, active && { color: '#fff' }]}>{label}</Text></Pressable>; }
function Action({ label, Icon = ArrowRight, onPress, light = false }: { label: string; Icon?: typeof ArrowRight; onPress: () => void; light?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={[s.action, light && s.lightAction]}><Text style={[s.actionText, light && { color: theme.blue }]}>{label}</Text><Icon size={17} color={light ? theme.blue : '#FFF'} /></Pressable>; }
function ListingIcon({ item, large = false }: { item: CareListing; large?: boolean }) { const Icon = icons[item.kind]; return <View style={[s.listingIcon, { backgroundColor: colors[item.kind][0] }, large && { width: 76, height: 76, borderRadius: 22 }]}><Icon size={large ? 35 : 25} color={colors[item.kind][1]} /></View>; }

export function DirectoryHome({ directory, loading, onBrowse, onGuide, onDemo }: { directory: CareDirectory; loading: boolean; onBrowse: (kind?: Kind, specialty?: string) => void; onGuide: () => void; onDemo: () => void }) {
  const wide = useWindowDimensions().width > 850;
  const count = (kind: Kind) => directory.listings.filter(i => kind === 'All' || i.kind === kind).length;
  return <View style={{ gap: 26 }}>
    <View style={s.headingRow}><View style={{ gap: 8 }}><Text style={s.kicker}>YOUR EVERYDAY CARE COMPANION</Text><Text style={[s.greeting, wide && { fontSize: 33 }]}>Good health starts with the right care.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="View care area" onPress={() => onBrowse()} style={s.location}><MapPin size={17} color={theme.blue} /><View><Text style={s.tiny}>SEARCH AREA</Text><Text style={s.locationName}>{directory.region || 'Location needed'}</Text></View></Pressable></View>
    <View style={[s.heroGrid, wide && { flexDirection: 'row' }]}>
      <View style={[s.hero, wide && { flex: 1.6 }]}><View style={s.heroCircle1} /><View style={s.heroCircle2} /><View style={s.heroBadge}><View style={s.dot} /><Text style={s.heroBadgeText}>A CLEARER WAY TO FIND CARE</Text></View><Text style={[s.heroTitle, wide && { fontSize: 45, lineHeight: 53 }]}>The right care.{ '\n' }Closer to you.</Text><Text style={s.heroDescription}>Find doctors, hospitals and clinics.{ '\n' }Get the details. Take your next step.</Text><Pressable accessibilityRole="button" accessibilityLabel="Find local care" onPress={() => onBrowse()} style={s.heroSearch}><Search size={21} color={theme.blue} /><Text style={s.heroSearchText}>Doctor, specialty or hospital</Text><View style={s.searchArrow}><ArrowRight size={19} color="#fff" /></View></Pressable><View style={s.heroProof}><ShieldCheck size={16} color="#C8D7FF" /><Text style={s.heroProofText}>Public sources · Direct provider contact</Text></View></View>
      <View style={[s.guideCard, wide && { flex: 1 }]}><View style={s.between}><View style={s.guideIcon}><Sparkles size={25} color={theme.blue} /></View><Text style={s.beta}>RESEARCH PREVIEW</Text></View><Text style={s.guideTitle}>A little guidance{ '\n' }for your next step.</Text><Text style={s.body}>Describe your symptoms and explore departments to discuss with clinic staff.</Text><Action label="Start symptom guide" onPress={onGuide} /><Text style={s.tiny}>Experimental suggestions. Not a diagnosis.</Text></View>
    </View>
    <View style={{ gap: 16 }}><View style={s.sectionHeader}><Text style={s.h2}>What kind of care do you need?</Text><Text style={s.small}>Explore your options</Text></View><View style={s.categories}>{(['Doctor', 'Hospital', 'Clinic'] as const).map(kind => { const Icon = icons[kind]; return <Pressable accessibilityRole="button" accessibilityLabel={`Browse ${kind.toLowerCase()}s`} onPress={() => onBrowse(kind)} key={kind} style={s.category}><View style={[s.categoryIcon, { backgroundColor: colors[kind][0] }]}><Icon size={26} color={colors[kind][1]} /></View><Text style={s.categoryTitle}>{kind === 'Doctor' ? 'Doctors' : kind === 'Hospital' ? 'Hospitals' : 'Clinics'}</Text><Text style={s.small}>{loading ? 'Loading…' : `${count(kind)} listed`}</Text><ChevronRight style={s.categoryArrow} size={17} color={theme.muted} /></Pressable>; })}</View></View>
    <View style={{ gap: 16 }}><View style={s.sectionHeader}><View style={{ gap: 5 }}><Text style={s.h2}>{directory.region ? `Care in ${directory.region}` : 'Your local care directory'}</Text><Text style={s.small}>Explore listings and check details directly with the provider.</Text></View><Pressable accessibilityRole="button" onPress={() => onBrowse()}><Text style={s.link}>View directory →</Text></Pressable></View>{loading ? <ActivityIndicator color={theme.blue} /> : directory.listings.length ? <View style={[s.featuredRow, wide && { flexDirection: 'row' }]}>{directory.listings.filter(i => i.kind !== 'Doctor').slice(0, 3).map(item => <Pressable accessibilityRole="button" accessibilityLabel={`Explore ${item.name}`} key={item.id} onPress={() => onBrowse(item.kind)} style={s.featured}><ListingIcon item={item} /><Text style={s.h3}>{item.name}</Text><Text style={s.small}>{item.locality} · {item.kind}</Text><Text style={s.body} numberOfLines={2}>{item.specialties.join(' · ')}</Text><View style={s.row}><ShieldCheck size={14} color={theme.blue} /><Text style={s.sourceLabel}>Public source linked</Text></View></Pressable>)}</View> : <View style={s.pending}><MapPin color={theme.blue} size={25} /><View style={{ flex: 1, gap: 6 }}><Text style={s.h3}>Let’s find care in your area</Text><Text style={s.body}>Your city or postcode is needed to add the right local listings. Your exact address is not required.</Text></View></View>}</View>
    <View style={s.demoStrip}><View style={s.demoStripIcon}><HeartPulse size={24} color={theme.blue} /></View><View style={{ flex: 1, gap: 5 }}><Text style={s.h3}>See the complete visit experience</Text><Text style={s.small}>Try appointment booking and queue tracking with fictional providers.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Try booking demo" onPress={onDemo} style={s.demoLink}><Text style={s.link}>Try demo</Text><ArrowRight size={17} color={theme.blue} /></Pressable></View>
  </View>;
}

export function Directory({ directory, initialKind = 'All', initialSpecialty = 'All', onDemo, onRetry, loading }: { directory: CareDirectory; initialKind?: Kind; initialSpecialty?: string; onDemo: () => void; onRetry: () => void; loading: boolean }) {
  const wide = useWindowDimensions().width > 850;
  const [kind, setKind] = useState<Kind>(initialKind), [specialty, setSpecialty] = useState(initialSpecialty), [query, setQuery] = useState('');
  const [selected, setSelected] = useState<CareListing | null>(null), [saved, setSaved] = useState<string[]>([]), [onlySaved, setOnlySaved] = useState(false), [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  useEffect(() => { AsyncStorage.getItem('carelane-saved-places-v1').then(raw => { if (raw) { const value = JSON.parse(raw); if (Array.isArray(value)) setSaved(value.filter(id => typeof id === 'string')); } }).catch(() => setError('Saved places could not be loaded on this device.')); }, []);
  async function save(item: CareListing) { if (saving) return; setSaving(true); const next = saved.includes(item.id) ? saved.filter(id => id !== item.id) : [...saved, item.id]; try { await AsyncStorage.setItem('carelane-saved-places-v1', JSON.stringify(next)); setSaved(next); } catch { setError('This place could not be saved. Please try again.'); } finally { setSaving(false); } }
  async function open(url: string) { try { await Linking.openURL(url); } catch { setError('This link could not be opened. Use the provider details shown here.'); } }
  const specialties = ['All', ...new Set(directory.listings.flatMap(i => i.specialties)), ...(initialSpecialty !== 'All' && !directory.listings.some(i => i.specialties.includes(initialSpecialty)) ? [initialSpecialty] : [])];
  const filtered = directory.listings.filter(i => (kind === 'All' || i.kind === kind) && (specialty === 'All' || i.specialties.includes(specialty)) && (!onlySaved || saved.includes(i.id)) && `${i.name} ${i.address} ${i.affiliation || ''} ${i.specialties.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  return <View style={{ gap: 22 }}>
    {!!error && <View style={s.error} accessibilityRole="alert"><Text style={{ flex: 1, color: '#983D31' }}>{error}</Text><Pressable accessibilityRole="button" accessibilityLabel="Dismiss directory error" onPress={() => setError('')}><X size={18} color="#983D31" /></Pressable></View>}
    {selected ? <>
      <Pressable accessibilityRole="button" accessibilityLabel="Back to directory" onPress={() => setSelected(null)} style={s.row}><ArrowLeft size={18} color={theme.blue} /><Text style={s.link}>Back to directory</Text></Pressable>
      <View style={s.detailHero}><View style={s.between}><ListingIcon item={selected} large /><Pressable accessibilityRole="button" accessibilityLabel={saved.includes(selected.id) ? 'Unsave place' : 'Save place'} onPress={() => void save(selected)} style={s.saveButton}><Bookmark size={23} color={theme.blue} fill={saved.includes(selected.id) ? theme.blue : 'none'} /></Pressable></View><Text style={s.kicker}>{selected.kind.toUpperCase()} · {selected.city.toUpperCase()}</Text><Text style={s.detailTitle}>{selected.name}</Text>{!!selected.affiliation && <Text style={s.body}>{selected.affiliation}</Text>}<View style={s.wrap}>{selected.specialties.map(v => <Text style={s.specialtyTag} key={v}>{v}</Text>)}</View></View>
      <View style={[s.detailGrid, wide && { flexDirection: 'row' }]}><View style={[s.panel, { flex: 1.4 }]}><Text style={s.h2}>About this {selected.kind.toLowerCase()}</Text><Text style={s.body}>{selected.description}</Text><View style={s.divider} /><Text style={s.h3}>Visit address</Text><View style={s.rowTop}><MapPin size={19} color={theme.blue} /><Text style={[s.body, { flex: 1 }]}>{selected.address}</Text></View><Action label="Get directions" Icon={Navigation} light onPress={() => void open(mapsUrl(selected))} /><Text style={s.tiny}>Opens a place search in Google Maps. Confirm the destination before travelling.</Text></View><View style={[s.panel, { flex: 1 }]}><Text style={s.h2}>Contact the provider</Text><Text style={s.body}>Confirm consultation times, fees and availability directly.</Text>{selected.phone ? <><Text style={s.phone}>{selected.phone}</Text><Action label="Call provider" Icon={Phone} onPress={() => void open(`tel:${selected.phone!.replace(/[^+\d]/g, '')}`)} /></> : <Text style={s.small}>A telephone number was not confirmed in the linked source.</Text>}<Action label="Open official website" Icon={ExternalLink} light onPress={() => void open(selected.website)} /><View style={s.infoBox}><ShieldCheck size={19} color={theme.blue} /><Text style={[s.small, { flex: 1 }]}>This app lists public information. It is not partnered with this provider and cannot confirm a booking here.</Text></View></View></View>
      <View style={s.panel}><View style={s.row}><ShieldCheck size={20} color={theme.blue} /><Text style={s.h3}>Where these details came from</Text></View><Text style={s.small}>Source checked {selected.checked_at}. Public listings may change; confirm before visiting.</Text>{selected.sources.map(source => <Pressable accessibilityRole="link" accessibilityLabel={source.title} key={source.url} onPress={() => void open(source.url)} style={s.sourceRow}><Text style={[s.link, { flex: 1 }]}>{source.title}</Text><ExternalLink size={16} color={theme.blue} /></Pressable>)}</View>
    </> : <>
      <View style={s.headingRow}><View style={{ gap: 7 }}><Text style={s.kicker}>FIND CARE · {directory.region?.toUpperCase() || 'SET YOUR AREA'}</Text><Text style={s.pageTitle}>Your local care directory</Text><Text style={s.body}>Real providers. Useful details. A clearer next step.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Show saved places" accessibilityState={{ selected: onlySaved }} onPress={() => setOnlySaved(!onlySaved)} style={[s.savedControl, onlySaved && { backgroundColor: theme.pale }]}><Bookmark size={18} color={theme.blue} /><Text style={s.link}>Saved ({saved.length})</Text></Pressable></View>
      <View style={s.directorySearch}><Search size={21} color={theme.blue} /><TextInput accessibilityLabel="Search local care" placeholder="Search name, specialty or area" placeholderTextColor={theme.muted} value={query} onChangeText={setQuery} style={s.searchInput} />{!!query && <Pressable accessibilityRole="button" accessibilityLabel="Clear search" onPress={() => setQuery('')}><X size={18} color={theme.muted} /></Pressable>}</View>
      <View style={s.wrap}>{(['All', 'Doctor', 'Hospital', 'Clinic'] as Kind[]).map(k => <Chip key={k} label={k === 'All' ? 'All care' : `${k}s`} active={kind === k} onPress={() => setKind(k)} />)}</View>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}><View style={s.row}><Text style={s.tiny}>SPECIALTY</Text>{specialties.map(v => <Chip key={v} label={v === 'All' ? 'All specialties' : v} active={specialty === v} onPress={() => setSpecialty(v)} />)}</View></ScrollView>
      <View style={s.between}><Text style={s.small}>{filtered.length} {onlySaved ? 'saved ' : ''}listing{filtered.length !== 1 ? 's' : ''}{directory.region ? ` in ${directory.region}` : ''}</Text><View style={s.row}><ShieldCheck size={14} color={theme.blue} /><Text style={s.sourceLabel}>Sources included</Text></View></View>
      {loading ? <ActivityIndicator color={theme.blue} /> : filtered.length ? <View style={s.results}>{filtered.map(item => <View style={[s.resultCard, wide && { width: '48.8%' }]} key={item.id}><View style={s.between}><ListingIcon item={item} /><Pressable accessibilityRole="button" accessibilityLabel={`${saved.includes(item.id) ? 'Unsave' : 'Save'} ${item.name}`} onPress={() => void save(item)} style={s.saveButton}><Bookmark size={20} color={saved.includes(item.id) ? theme.blue : '#95A0B5'} fill={saved.includes(item.id) ? theme.blue : 'none'} /></Pressable></View><View style={{ gap: 8 }}><Text style={s.kind}>{item.kind}</Text><Text style={s.h3}>{item.name}</Text><Text style={s.body}>{item.specialties.join(' · ')}</Text>{!!item.affiliation && <Text style={s.small}>{item.affiliation}</Text>}<View style={s.rowTop}><MapPin size={14} color={theme.muted} /><Text style={[s.small, { flex: 1 }]}>{item.locality} · {item.city}</Text></View></View><View style={s.resultFooter}><Text style={s.sourceLabel}>Public listing</Text><Pressable accessibilityRole="button" accessibilityLabel={`View details for ${item.name}`} onPress={() => setSelected(item)} style={s.row}><Text style={s.link}>View details</Text><ArrowRight size={16} color={theme.blue} /></Pressable></View></View>)}</View> : <View style={s.empty}><Search color={theme.blue} size={32} /><Text style={s.h2}>{directory.region ? 'No matching listings' : 'Location needed'}</Text><Text style={[s.body, { textAlign: 'center' }]}>{directory.region ? 'Try another specialty, clear your search or turn off Saved.' : 'Tell us your city or postcode so the right doctors, hospitals and clinics can be added.'}</Text>{directory.region ? <Action label="Clear directory filters" light onPress={() => { setKind('All'); setSpecialty('All'); setQuery(''); setOnlySaved(false); }} /> : <Action label="Refresh directory" light onPress={onRetry} />}</View>}
      <View style={s.infoBox}><ShieldCheck size={19} color={theme.blue} /><Text style={[s.small, { flex: 1 }]}>Listings are not rankings or endorsements. No live availability, ratings or distance are assumed. Use the provider’s official contact details to arrange care.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Try booking demo" onPress={onDemo}><Text style={s.link}>Explore the fictional booking & queue demo →</Text></Pressable>
    </>}
  </View>;
}

const s = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', gap: 8 }, rowTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 }, between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  headingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 18 }, kicker: { fontSize: 10, letterSpacing: 1.45, fontWeight: '700', color: theme.muted }, greeting: { fontSize: 26, lineHeight: 39, color: theme.navy, fontWeight: '600', letterSpacing: -.8 }, location: { backgroundColor: '#FFF', borderWidth: 1, borderColor: theme.line, borderRadius: 13, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10 }, locationName: { color: theme.navy, fontWeight: '600', fontSize: 13, marginTop: 3 }, tiny: { fontSize: 10, color: theme.muted, lineHeight: 17 },
  heroGrid: { gap: 20 }, hero: { backgroundColor: '#2554D6', padding: 29, borderRadius: 25, gap: 19, overflow: 'hidden' }, heroCircle1: { position: 'absolute', height: 370, width: 370, borderRadius: 200, borderWidth: 65, borderColor: '#3261DF', right: -205, top: -85 }, heroCircle2: { position: 'absolute', height: 240, width: 240, borderRadius: 150, backgroundColor: '#305DDA', right: -100, bottom: -125 }, heroBadge: { flexDirection: 'row', gap: 7, alignItems: 'center' }, dot: { height: 6, width: 6, backgroundColor: '#A8EED8', borderRadius: 4 }, heroBadgeText: { color: '#D5E2FF', fontSize: 9, letterSpacing: 1.3, fontWeight: '600' }, heroTitle: { fontSize: 35, lineHeight: 44, color: '#FFF', fontWeight: '600', letterSpacing: -1.2 }, heroDescription: { fontSize: 14, color: '#D4E1FF', lineHeight: 23 }, heroSearch: { borderRadius: 13, backgroundColor: '#FFF', padding: 9, paddingLeft: 14, flexDirection: 'row', gap: 10, alignItems: 'center', marginTop: 3 }, heroSearchText: { fontSize: 12, color: '#8590A8', flex: 1 }, searchArrow: { padding: 12, backgroundColor: '#183CA0', borderRadius: 10 }, heroProof: { flexDirection: 'row', alignItems: 'center', gap: 8 }, heroProofText: { color: '#C8D7FF', fontSize: 10 }, guideCard: { borderWidth: 1, borderColor: '#DCE5FB', backgroundColor: '#EEF3FF', borderRadius: 25, padding: 26, gap: 20, justifyContent: 'space-between' }, guideIcon: { padding: 12, borderRadius: 15, backgroundColor: '#FFF' }, beta: { color: '#6980B5', fontSize: 9, fontWeight: '700', letterSpacing: .7 }, guideTitle: { fontSize: 25, lineHeight: 34, color: theme.navy, fontWeight: '600', letterSpacing: -.7 },
  body: { color: '#66758F', fontSize: 13, lineHeight: 22 }, small: { color: theme.muted, fontSize: 11, lineHeight: 18 }, h2: { color: theme.navy, fontSize: 20, fontWeight: '600', letterSpacing: -.5 }, h3: { color: theme.navy, fontSize: 17, fontWeight: '600', lineHeight: 25 }, link: { color: theme.blue, fontSize: 12, fontWeight: '600', paddingVertical: 3 }, sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 9 },
  action: { backgroundColor: theme.blue, borderRadius: 11, minHeight: 46, paddingVertical: 13, paddingHorizontal: 17, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 }, lightAction: { backgroundColor: theme.pale }, actionText: { color: '#FFF', fontSize: 13, fontWeight: '600', flexShrink: 1 }, categories: { flexDirection: 'row', gap: 12 }, category: { flex: 1, minWidth: 0, backgroundColor: '#FFF', borderWidth: 1, borderColor: theme.line, borderRadius: 17, padding: 16, gap: 8 }, categoryIcon: { width: 47, height: 47, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginBottom: 5 }, categoryTitle: { color: theme.navy, fontSize: 14, fontWeight: '600' }, categoryArrow: { position: 'absolute', right: 13, top: 18 }, featuredRow: { gap: 15 }, featured: { flex: 1, backgroundColor: '#FFF', borderWidth: 1, borderColor: theme.line, borderRadius: 19, padding: 21, gap: 12 }, listingIcon: { height: 53, width: 53, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, sourceLabel: { fontSize: 10, color: '#7186AF' }, pending: { backgroundColor: '#FFF', borderRadius: 18, borderWidth: 1, borderColor: theme.line, padding: 22, flexDirection: 'row', gap: 17 }, demoStrip: { borderWidth: 1, borderColor: '#DBE5F6', backgroundColor: '#EDF3FD', borderRadius: 17, padding: 19, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 15 }, demoStripIcon: { backgroundColor: '#FFF', padding: 12, borderRadius: 13 }, demoLink: { flexDirection: 'row', gap: 6, alignItems: 'center', paddingVertical: 8 },
  pageTitle: { fontSize: 31, fontWeight: '600', color: theme.navy, letterSpacing: -.8, lineHeight: 41 }, savedControl: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: theme.line, paddingHorizontal: 13, paddingVertical: 10, backgroundColor: '#FFF', borderRadius: 11 }, directorySearch: { flexDirection: 'row', alignItems: 'center', gap: 11, borderWidth: 1, borderColor: '#D8E1F3', backgroundColor: '#FFF', borderRadius: 13, paddingHorizontal: 17 }, searchInput: { minHeight: 54, flex: 1, fontSize: 14, color: theme.navy }, chip: { paddingHorizontal: 15, paddingVertical: 11, backgroundColor: '#FFF', borderRadius: 10, borderWidth: 1, borderColor: theme.line }, chipActive: { backgroundColor: theme.blue, borderColor: theme.blue }, chipText: { fontSize: 12, color: '#687B9A', fontWeight: '500' }, results: { flexDirection: 'row', flexWrap: 'wrap', gap: 17 }, resultCard: { width: '100%', padding: 23, gap: 17, backgroundColor: '#FFF', borderWidth: 1, borderColor: theme.line, borderRadius: 20 }, saveButton: { padding: 10, borderRadius: 12, backgroundColor: '#F7F9FD' }, kind: { color: '#6582B7', fontSize: 10, textTransform: 'uppercase', letterSpacing: 1 }, resultFooter: { borderTopWidth: 1, borderColor: theme.line, paddingTop: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, infoBox: { flexDirection: 'row', gap: 11, padding: 17, backgroundColor: '#EBF1FD', borderRadius: 13 }, empty: { padding: 32, alignItems: 'center', gap: 17, backgroundColor: '#FFF', borderWidth: 1, borderColor: theme.line, borderRadius: 19 }, error: { padding: 15, backgroundColor: '#FCEDE7', flexDirection: 'row', gap: 10, borderRadius: 12 },
  detailHero: { padding: 27, gap: 19, backgroundColor: '#FFF', borderWidth: 1, borderColor: theme.line, borderRadius: 23 }, detailTitle: { fontSize: 30, lineHeight: 40, color: theme.navy, fontWeight: '600', letterSpacing: -.7 }, specialtyTag: { backgroundColor: theme.pale, color: '#526FAC', fontSize: 11, padding: 9, borderRadius: 8, overflow: 'hidden' }, detailGrid: { gap: 20 }, panel: { padding: 23, gap: 17, borderWidth: 1, borderColor: theme.line, borderRadius: 20, backgroundColor: '#FFF' }, divider: { height: 1, backgroundColor: theme.line }, phone: { fontSize: 20, color: theme.navy, fontWeight: '600' }, sourceRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 9 },
});
